name: Run Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Move to project directory
        run: cd luma-accordia/

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Set up Chrome browser
        uses: nanasess/setup-chromedriver@v2

      - name: Run tests
        run: |
          mvn -B clean test