name: Run Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set headless mode environment variable
        run: echo "headless_mode=true" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install unzip
        run: sudo apt-get install unzip

      - name: Download and setup ChromeDriver
        run: |
          cd luma-accordia/
          chmod +x webdriver_setup.sh
          ./webdriver_setup.sh

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Set up Chrome browser
        uses: nanasess/setup-chromedriver@v2


      - name: Download Allure CLI
        run: |
          wget -O allure-2.27.0.tgz https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.27.0/allure-commandline-2.27.0.tgz
          tar -zxvf allure-2.27.0.tgz

      - name: Add Allure CLI to PATH
        run: |
          sudo ln -s $(pwd)/allure-2.15.0/bin/allure /usr/bin/allure

      - name: Run Maven test
        run: mvn -B clean test -f luma-accordia/pom.xml
        continue-on-error: true

      - name: Generate Allure report
        run: allure generate luma-accordia/target/allure-results --output luma-accordia/target/allure-report

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: luma-accordia/target/allure-report